name: keypoint_moseq

channels:
  - conda-forge
  - nvidia
  - defaults

dependencies:
  - python=3.10
  - pytables
  - jaxlib=0.3.22=*cuda*
  - jax=0.3.22
  - cuda-nvcc=11.8.89
  - pip
  - pip:
    - "keypoint-moseq"
    - "jax-moseq[cuda11]"
    - jupyterlab
    - etils==1.5.2