name: keypoint_moseq

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10
  - pytables
  - conda-forge::jax=0.3.22
  - conda-forge::jaxlib=0.3.22=*cpu*
  - pip
  - pip:
    - "keypoint-moseq"
    - jupyterlab
    - etils==1.5.2
