name: keypoint_moseq

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.9
  - pytables
  - pip
  - pip:
    - jax==0.3.22
    - "https://whls.blob.core.windows.net/unstable/cpu/jaxlib-0.3.22-cp39-cp39-win_amd64.whl"
    - "jax-moseq"
    - "--editable=../"
    - jupyterlab
