name: keypoint_moseq

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.9
  - pytables
  - conda-forge::jax=0.3.22
  - conda-forge::jaxlib=0.3.22=*cpu*
  - pip
  - pip:
    - "jax-moseq==0.0.0"
    - "--editable=../"
    - jupyterlab
